---
nginx_user: "deployer"

proxy_to_app_address: "http://127.0.0.1:{{ app_port }}"

nginx_sites:
  default:
    - listen 80
    - server_name _
    - location / {
        root "/var/www/app/static";
        index index.html hello.html;
      }
    - location ~ /(api|upload)/ {
        proxy_pass {{ proxy_to_app_address }};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
